name: "Install Okapi Binaries"
description: "Install Okapi binaries on the github action runner"

runs:
  using: "composite"
  steps:
    - name: Download Libs
      run: |
        curl -H "Accept: application/vnd.github+json" -H "Authorization: ${{ secrets.API_GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/trinsic-id/okapi/releases/latest > okapi_release.json
        $myJson = Get-Content okapi_release.json -Raw | ConvertFrom-Json
        Write-Output $myJson
        $latestVersion = $myJson.name
        $downloadTarget = "https://github.com/trinsic-id/okapi/releases/download/$latestVersion/libs.zip"
        Write-Output "Version=$latestVersion, target=$downloadTarget"
        curl -L -o libs.zip "$downloadTarget"
        Expand-Archive -Path libs.zip -DestinationPath "${{ github.workspace }}"
      shell: pwsh