name: "Install Okapi Binaries"
description: "Install Okapi binaries on the github action runner"

runs:
  using: "composite"
  steps:
    - name: Download Libs
      run: |
        curl -L -o libs.zip https://github.com/trinsic-id/okapi/releases/download/v1.6.0/libs.zip
        Expand-Archive -Path libs.zip -DestinationPath ./libs
      shell: pwsh