AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - '**/*.rbi' # Don't look at sorbet type hints
    - 'lib/**/*_pb.rb' # don't check the generated code
    - 'test/**/*.rb' # Don't check tests
Layout/EndOfLine:
  Enabled: False