
image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-browser

tasks:
  - command: rustup component add rustfmt && cargo install --path cli
  - command: mkdocs serve -a 127.0.0.1:5000

vscode:
  extensions:
    - matklad.rust-analyzer
