
image:
  file: .gitpod.Dockerfile

# ports:
#   - port: 5000
#     onOpen: ignore

tasks:
  - command: rustup component add rustfmt && cargo install --path cli

vscode:
  extensions:
    - matklad.rust-analyzer
