site_name: "Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
site_url: https://ecosystems-docs-alpha.trinsic.id
nav:
  - Welcome: index.md
  - Join the Beta: early-adopter.md
  - Join the Community: https://join.slack.com/t/trinsiccommunity/shared_invite/zt-pcsdy7kn-h4vtdPEpqQUlmirU8FFzSQ
  - Have a Question?: support.md
  - Build:
    - CLI: build/cli/index.md
    - Node: build/node/index.md
    - C#: build/dotnet/index.md
    - Python: build/python/index.md
    - Ruby: build/ruby/index.md
    - Go: build/go/index.md
    - Java: build/java/index.md
    - Web: build/web/index.md
    - iOS: build/ios/index.md
    - Android: build/android/index.md
  - Learn:
    - Introduction: learn/index.md
    - Wallets: learn/wallets.md
    - Credentials: learn/credentials.md
    - Passes: learn/passes.md
    - Ecosystems: learn/ecosystems.md
    - Security: learn/security.md
    - Underlying Tech: learn/tech.md
  - Reference:
    - Setup: reference/setup/index.md
    - Wallet Service: reference/services/wallet-service.md
    - Provider Service: reference/services/provider-service.md
    - Trust Registry: reference/services/trust-registry.md
  - Resources:
    - Roadmap: roadmap.md
    - Changelog: changelog.md
    - Github: https://github.com/trinsic-id
theme:
  name: material
  logo: _static/logo-title.svg
  favicon: _static/logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/cloud-moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: [".", "docs"]
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
  - abbr

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - _static/javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs.min.css
  - _static/extra.css

extra:
  generator: false
