site_name: Docs
site_dir: docs-site
extra_css: 
  - _static/extra.css
theme:
    name: material
    logo: _static/logo-title.svg
    favicon: _static/logo.png
    highlightjs: true
    hljs_languages:
        - yaml
        - rust