site_name: "Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
site_url: https://ecosystems-docs-alpha.trinsic.id
nav:
  - Home: index.md
  - Getting Started: 
    - What is Trinsic?: learn/intro.md
    - Before You Start: early-adopter.md
    - Try the Walkthrough: walkthroughs/vaccination.md
  - Key Concepts:
    - Wallets: learn/wallets.md
    - Templates: learn/templates.md
    - Credentials: learn/credentials.md
    - Ecosystems: learn/ecosystems.md
    - Standards: learn/standards.md
    - Security: learn/security.md
  - Developer Tools:
    - Trinsic CLI: cli/index.md
    - Client-Side SDKs:
      - Browser: web/index.md
      - iOS: ios/index.md
      - Android: android/index.md
    - Server-Side SDKs:
      - Node: node/index.md
      - C#: dotnet/index.md
      - Python: python/index.md
      - Ruby: ruby/index.md
      - Go: go/index.md
      - Java: java/index.md
  - SDK Reference:
    - Setup & Configuration: reference/index.md
    - Wallet Service: reference/services/wallet-service.md
    - Credential Service: reference/services/credential-service.md
    - Provider Service: reference/services/provider-service.md
    - Trust Registry Service: reference/services/trust-registry-service.md
    - Protocol Buffers: reference/proto/index.md
  - Resources:
    - Roadmap: roadmap.md
    - Ask a Question: support.md
    - Join the Community: https://join.slack.com/t/trinsiccommunity/shared_invite/zt-pcsdy7kn-h4vtdPEpqQUlmirU8FFzSQ
    # - Changelog: changelog.md
    - Contribute on Github: https://github.com/trinsic-id
theme:
  name: material
  logo: _static/logo-title.svg
  custom_dir: overrides
  favicon: _static/logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    # - navigation.expand
    # - navigation.sections
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/cloud-moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: false
  - pymdownx.snippets:
      base_path: [".", "docs"]
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - _static/javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs.min.css
  - _static/extra.css

extra:
  generator: false

plugins:
  - search
  - autorefs
  - codeinclude:
      title_mode: none
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('python')
            - sys.path.append('python/trinsic')
          selection:
            new_path_syntax: true
      watch:
        - python
