site_name: "Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
site_url: https://ecosystems-docs-alpha.trinsic.id
nav:
  - Overview: index.md
  - Concepts: concepts/index.md
  - Start Building:
    - CLI: walkthrough/vaccination-cli.md
    - Node: walkthrough/vaccination-node.md
    - Web: walkthrough/vaccination-browser.md
    - C#: walkthrough/vaccination-net.md
    - Python: walkthrough/vaccination-python.md
  - Reference:
    - Setup: reference/setup/index.md
    - Wallet Service: reference/services/wallet-service.md
    - Provider Service: reference/services/provider-service.md
  - Support:
    - Join Slack Community: https://join.slack.com/t/trinsiccommunity/shared_invite/zt-pcsdy7kn-h4vtdPEpqQUlmirU8FFzSQ
    - Contribute on Github: https://github.com/trinsic-id
    - Email us: mailto:support@trinsic.id
  - What's Next:
    - Join Trinsic Ecosystems: early-adopter.md
theme:
  name: material
  logo: _static/logo-title.svg
  favicon: _static/logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/cloud-moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: [".", "docs"]
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 2
  - abbr

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - _static/javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs.min.css
  - _static/extra.css

extra:
  generator: false
