site_name: "Ecosystems Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
nav:
  - Getting Started:
      - Introduction: index.md
      - Walkthrough: walkthrough.md
  - Reference:
      - Overview: reference/index.md
      - Installation: reference/installation.md
      - Concepts:
        - Security Profiles: reference/profiles.md
        - Configuration: reference/configuration.md
      - Services:
          - Wallet Service: reference/services/wallet-service.md
          - Provider Service: reference/services/provider-service.md
  - FAQ: faq.md
theme:
    name: material
    logo: _static/logo-title.svg
    favicon: _static/logo.png
    features:
      - content.tabs.link
      - navigation.sections
      - navigation.tabs
      - navigation.tracking
    icon:
      repo: fontawesome/brands/github-alt
    font:
      text: Inter
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: fontawesome/solid/cloud-moon
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: fontawesome/solid/sun
          name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - toc:
      permalink: true
  - abbr
extra_css:
  - _static/extra.css
plugins:
  - tags