site_name: "Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
site_url: https://docs-v2.trinsic.id
nav:
  - Home:
    - Introduction: index.md
    - Join the Beta: early-adopter.md
  - Learn: 
    - Overview: learn/index.md
    - Key Concepts:
      - Identity Ecosystems: learn/concepts/ecosystems.md
      - Credentials: learn/concepts/credentials.md
      - Trust Registries: learn/concepts/trust-registries.md
      - Standards: learn/concepts/standards.md
    - Trinsic Platform:
      - What is Trinsic?: learn/platform/intro.md
      - Security Overview: learn/platform/security.md
      - Templates: learn/platform/templates.md
      - Wallets: learn/platform/wallets.md
      - Webhooks: learn/platform/webhooks.md
    - Tutorials:
      - Build a Vaccine Card: walkthroughs/vaccination.md
  - Reference:
    - Overview: reference/index.md
    - SDK Services:
      - Account Service: reference/services/account-service.md
      - Credential Service: reference/services/credential-service.md
      - Provider Service: reference/services/provider-service.md
      - Template Service: reference/services/template-service.md
      - Trust Registry Service: reference/services/trust-registry-service.md
      - Wallet Service: reference/services/wallet-service.md
      - Protocol Buffers Reference: reference/proto/index.md
    - Other Services:
      - OpenID Credential Exchange: reference/other/openid.md
    - Events Reference: reference/events.md
  - Tools & SDKs:
    - Trinsic CLI: cli/index.md
    - Client-Side SDKs:
      - Browser: web/index.md
      - iOS: ios/index.md
      - Android: android/index.md
    - Server-Side SDKs:
      - Node: node/index.md
      - C#: dotnet/index.md
      - Python: python/index.md
      - Ruby: ruby/index.md
      - Go: go/index.md
      - Java: java/index.md
  - Resources:
    - Roadmap: roadmap.md
    - Ask a Question: support.md
    - Join the Community: https://join.slack.com/t/trinsiccommunity/shared_invite/zt-pcsdy7kn-h4vtdPEpqQUlmirU8FFzSQ
    # - Changelog: changelog.md
    - Contribute on GitHub: https://github.com/trinsic-id
theme:
  name: material
  logo: _static/logo-title.svg
  custom_dir: docs/overrides
  favicon: _static/logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    # - navigation.expand
    - navigation.sections
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/cloud-moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: [".", "docs"]
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - markdown.extensions.md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - _static/javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs.min.css
  - _static/extra.css

extra:
  generator: false

plugins:
  - search
  - macros:
      module_name: mkdocs_macros_main
      verbose: true
  - autorefs
  - git-authors:
      show_contribution: false
      show_line_count: true
      fallback_to_empty: false
      sort_authors_by: "contribution"
      authorship_threshold_percent: 10
      exclude:
          - index.md
      enabled: true
  - codeinclude:
      title_mode: none
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('python')
            - sys.path.append('python/trinsic')
          selection:
            new_path_syntax: true
      watch:
        - python
        - mkdocs_macros_main.py
