site_name: Documentation
site_dir: docs-site
repo_url: https://github.com/trinsic-id/sdk
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk

nav:
  - Introduction: index.md
  - Walkthrough: walkthrough.md
  - Reference: reference.md

theme:
    name: material
    logo: _static/logo-title.svg
    favicon: _static/logo.png
    icon:
      repo: fontawesome/brands/github-alt
    font:
      text: Inter
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: fontawesome/solid/cloud-moon
          name: Switch to dark mode
        
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: fontawesome/solid/sun
          name: Switch to light mode
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

extra_css: 
  - _static/extra.css