name: trinsic-dart
description: Dart wrapper for the trinsic services SDK
version: 0.1.0
homepage: https://trinsic.id

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
