name: trinsic_dart
description: Dart wrapper for the trinsic services SDK
version: "1.13.0"
homepage: https://trinsic.id

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  protobuf: ^3.0.0
  grpc: ^3.2.3
  uuid: ^3.0.7
  fixnum: ^1.1.0

dev_dependencies:
  lints: 2.1.1
  test: 1.25.5
  path: any
  coverage: 1.8.0
