name: trinsic_dart
description: Dart wrapper for the trinsic services SDK
version: "1.11.0"
homepage: https://trinsic.id

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  protobuf: ^2.1.0
  grpc: ^3.1.0
  uuid: ^3.0.7
  fixnum: ^1.1.0

dev_dependencies:
  lints: any
  test: 1.24.1
  path: any
  coverage: 1.3.2
