# This space intentionally left blank
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  npmName: "@trinsic/connect"
  npmVersion: "0.0.4"
