additionalProperties:
  pubAuthor: Trinsic
  pubAuthorEmail: engineering@trinsic.id
  pubName: TrinsicConnect
#  pubShortDescription:
  pubVersion: 0.0.1
  disallowAdditionalPropertiesIfNotPresent: false
