additionalProperties:
  # https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/csharp.md
  packageVersion: 0.0.2
  packageName: Trinsic.Connect
  packageTitle: Trinsic Connect SDK
  packageCompany: trinsic.id
  packageAuthors: Trinsic
  packageDescription: Trinsic Connect SDK
  packageRepositoryUrl: https://github.com/trinsic-id/sdk.git
  packageGuid: eae0c21a-20c5-476c-b681-16260b12bf24 # This prevents `openapi-generator-cli` from generating a new GUID each time
  netCoreProjectFile: true
  optionalProjectFile: true
  library: httpclient
  validatable: false
  optionalAssemblyInfo: true
  targetFramework: net8.0
