additionalProperties:
  # https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/csharp.md
  packageVersion: 0.0.1
  packageName: Trinsic.Connect
  netCoreProjectFile: true
  optionalProjectFile: true
  library: httpclient
  optionalAssemblyInfo: true
  targetFramework: net8.0
