additionalProperties:
  # https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/csharp.md
  packageVersion: 0.0.2
  packageName: Trinsic.Connect
  packageTitle: Trinsic Connect SDK
  packageCompany: trinsic.id
  packageAuthors: Trinsic
  packageDescription: Trinsic Connect SDK
  packageRepositoryUrl: https://github.com/trinsic-id/sdk.git
  netCoreProjectFile: true
  optionalProjectFile: true
  library: httpclient
  validatable: false
  optionalAssemblyInfo: true
  targetFramework: net8.0
