name: Dart

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "dart/**"
      - "proto/**"
      - ".github/workflows/build-dart*"
      - ".github/workflows/release-dart*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "dart/**"
      - "proto/**"
      - "devops/**"

jobs:
  build-and-test-dart:
    name: Test Dart code
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]  # ,macos-latest ] - as usual, macos blocks DLL execution lol
    steps:
      - uses: actions/checkout@v3
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Dart analyze
        run: |
          dart pub get
          dart analyze
          dart pub global activate coverage
          dart run coverage:test_with_coverage
        shell: pwsh
        working-directory: dart
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
