name: "Connect SDK / Dotnet"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'connect/swagger**'
      - '.github/workflows/build-connect-dotnet.yaml'
      - "devops/**"

jobs:
  build_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Connect Dotnet SDK
        run: ./.github/workflows/connect/build-dotnet.ps1
        shell: pwsh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
