name: Java

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"

jobs:
  build-and-test-java:
    name: Build
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows], [macos-latest, macos] ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Download ${{ matrix.os-artifact[0] }} binaries
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          workflow: "build-libs.yml"
          path: ./libs/${{ matrix.os-artifact[1] }}
          repo: trinsic-id/okapi
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ matrix.os-artifact[1] }}
          workflow_conclusion: completed
      - name: Build with Gradle
        run: |
          python ../devops/build_sdks.py --language=java
          gradle build --stacktrace --debug
        shell: pwsh
        working-directory: java
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This has github maven package repo permissions
          OKAPI_LIBRARY_PATH: "${{ github.workspace }}/libs"
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          directory: java/build/reports/jacoco/test
          token: ${{ secrets.CODECOV_TOKEN }}
