name: Build/Test Documentation

on:
  workflow_call:
  pull_request:
    # We don't have path dependencies because we code-inject the samples, and we want to ensure those are all in the right places.
    paths-ignore:
      - 'connect/**'
      - '.github/workflows/build-connect-*.yaml'
      - '.github/workflows/release-connect-*.yml'
      - '.github/workflows/pr-validate-connect.yaml'
      - '.github/workflows/connect/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs build

