name: "Connect SDK / Typescript"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'connect/swagger**'
      - '.github/workflows/build-connect-typescript.yaml'
      - "devops/**"

jobs:
  build_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Setup Node v20
        with:
          node-version: 20
          cache: 'npm'

      - name: Build Connect TypeScript SDK
        run: ./.github/workflows/connect/build-typescript.ps1
        shell: pwsh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
