name: Golang

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "go/**"
      - "proto/**"
      - ".github/workflows/*golang*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "go/**"
      - "proto/**"
      - ".github/workflows/*golang*"
      - "devops/**"

jobs:
  build-and-test-golang:
    name: Build, Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: go/go.sum
      - name: Build and Test Golang
        run: |
          go version
          go test -covermode "atomic" -coverprofile "coverage.txt"
        working-directory: go/services
        shell: pwsh
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
