name: Rust

on:
  workflow_call:
  pull_request:
    paths:
      - "cli/**"
      - "proto/**"
      - ".github/workflows/*rust*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "cli/**"
      - "proto/**"
      - ".github/workflows/*rust*"
      - "devops/**"
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  rust:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v3
      - name: Build and test Rust
        run: |
          rustup component add rustfmt
          cargo build
          cargo test
      - name: Test CLI directly
        run: |
          ./test/Run-Demo.ps1 -Environment Staging -CommandPath ./target/debug/trinsic
        shell: pwsh