name: Rust

on:
  workflow_call:
  pull_request:
    paths:
      - "cli/**"
      - "proto/**"
      - ".github/workflows/*rust*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "cli/**"
      - "proto/**"
      - ".github/workflows/*rust*"
      - "devops/**"
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  rust:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test CLI directly
        run: |
          ./test/Run-Demo.ps1 -Environment Staging -CommandPath ./target/debug/trinsic
        shell: pwsh