name: "Connect SDK / Typescript"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'connect/swagger**'
      - '.github/workflows/build-connect-typescript.yaml'
      - "devops/**"

jobs:
  build_test:
    strategy:
      matrix:
        swagger_json: ['connect/swagger_api.json']
        language: [['typescript-fetch', 'connect/typescript']]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Setup Node v20
        with:
          node-version: 20
          cache: 'npm'

      - name: Build Connect TypeScript SDK
        run: ./connect/make-swagger.ps1 -language ${{ matrix.language[0] }} -swaggerFile ${{ matrix.swagger_json }} -outputFolder ${{ matrix.language[1] }}
        shell: pwsh

      - name: Build and format
        run: ./.github/workflows/connect/build-typescript.ps1
        shell: pwsh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
