name: Java

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"

jobs:
  build-and-test-java:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: |
          gradle build --scan
        shell: pwsh
        working-directory: java
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This has github maven package repo permissions
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
