name: Python

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "python/**"
      - "proto/**"
      - ".github/workflows/*python*"
  push:
    branches:
      - main

jobs:
  test_python:
    name: Test Python code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build, Test, Pack
        run: ./devops/BuildPython.ps1 -GitTag ${{ github.ref }} -UseDevelopOkapi
        shell: pwsh
        env:
          TRINSIC_SERVER_ADDRESS: http://trinsic-staging.centralus.azurecontainer.io:5000/
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: |
            ./python/pytest*.*

  upload_test_results:
    name: Upload Python Test Results
    runs-on: ubuntu-latest
    needs: [test_python]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: pytest-results
          path: python
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        if: always()
        with:
          files: python/pytest_junit.xml