name: "Connect/TypeScript"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'connect/swagger**'
      - '.github/workflows/*typescript*'
      - "devops/**"

jobs:
  build_test:
    # TODO - Matrix all possible swagger_jsons?
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Setup Node v20
        with:
          node-version: 20
          cache: 'npm'
      - name: Build Connect TypeScript SDK
        run: ./devops/make-swagger.ps1 -language typescript-fetch -swaggerFile ./connect/swagger_api.json -outputFolder ./connect/typescript
        shell: pwsh

      - uses: stefanzweifel/git-auto-commit-action@v4
