name: Ruby

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "ruby/**"
      - "proto/**"
      - ".github/workflows/*ruby*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "ruby/**"
      - "proto/**"
      - ".github/workflows/*ruby*"
      - "devops/**"

jobs:
  build-and-test-ruby:
    name: Build, Test
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows], [macos-latest, macos] ]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby-version: [ '3.0', '3.1' ]
        exclude:
          # Windows 3.1 has a mingw error with grpc upstream
          - os-artifact: [windows-latest, windows]
            ruby-version: '3.1'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          python ../devops/build_sdks.py --language=ruby
          bundle exec rake
        shell: pwsh
        working-directory: ruby
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
