name: Build Proto Files
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "proto/**"
      - "devops/**"
      - ".github/workflows/build-proto.yml"

jobs:
  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: trinsic-id/protoc-gen-sdk@main
        id: buildsdkwrappers
      - name: Install protobuf plugins
        run: |
          pip install -r ./devops/requirements.txt
          python ./devops/generate_proto_files.py --download-plugins --language=none
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Compile proto files
        run: |
          python ./devops/generate_proto_files.py --language=all

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Mewmba
          author_email: mewmba@trinsic.id
          message: 'Generated code from proto files on branch ${{ github.head_ref }}'
          new_branch: '${{ github.head_ref }}-generated-protos'
          push: '--force --set-upstream origin ${{ github.head_ref }}-generated-protos'

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "mewmba-${{ github.head_ref }}-generated-protos"  # From previous step
          destination_branch: ${{ github.head_ref }}
          pr_title: "Generated Protos for ${{ github.head_ref }}"
          pr_body: ":rocket: Generated protos"
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
