name: Python (build)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "python/**"
      - "proto/**"
      - ".github/workflows/*python*"
  push:
    branches:
      - main

jobs:
  test_python:
    name: Test Python code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build, Test, Pack
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov
          python ../devops/build_sdks.py --github-token=${{ secrets.API_GITHUB_TOKEN }}
          python -m pytest --cache-clear ./tests --junitxml=test_output.xml --cov=.
        shell: pwsh
        working-directory: python
        env:
          TRINSIC_SERVER_ADDRESS: http://20.75.134.127:80/
      - name: Upload Unit Test Results - Python
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Python ${{ matrix.python-version }} Unit Test Results (${{ matrix.os }})
          path: 'python/test_output*.xml'

  upload_test_results:
    name: Upload Python Test Results
    runs-on: ubuntu-latest
    needs: [test_python]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: pytest-results
          path: python
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        if: always()
        with:
          files: python/pytest_junit.xml