name: Dart

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "dart/**"
      - "proto/**"
      - ".github/workflows/*dart*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "dart/**"
      - "proto/**"
      - ".github/workflows/*dart*"
      - "devops/**"

jobs:
  build-and-test-dart:
    name: Test Dart code
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows]]  # , [macos-latest, macos] ] - as usual, macos blocks DLL execution lol
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/install-okapi-binaries-action  # We cannot put action.yaml in `.github/workflows` dir
        id: install_okapi_binaries
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Build, Test, Pack
        run: |
          dart pub get
          python ../devops/build_sdks.py --language=dart
          dart pub global activate coverage
          dart run coverage:test_with_coverage
        shell: pwsh
        working-directory: dart
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"