name: Build Proto Files
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "proto/**"
      - "devops/*"
  pull_request:
    paths:
      - "proto/**"
      - "devops/**"
      - ".github/workflows/build-proto.yml"

jobs:
  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: trinsic-id/protoc-gen-sdk@main
        id: buildsdkwrappers
        with:
          protoPath: ${{ github.workspace }}/proto
          dartPath: ${{ github.workspace }}/dart
          dotnetPath: ${{ github.workspace }}/dotnet
          golangPath: ${{ github.workspace }}/go
          javaKotlinPath: ${{ github.workspace }}/java
          pythonPath: ${{ github.workspace }}/python
          rubyPath: ${{ github.workspace }}/ruby
          typescriptPath: ${{ github.workspace }}/web
      - name: Install protobuf plugins
        run: |
          pip install -r ./devops/requirements.txt
          python ./devops/generate_proto_files.py --download-plugins --language=none
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Compile proto files
        run: |
          python ./devops/generate_proto_files.py --language=all

      - name: Create new branch name
        id: new-branch-name
        run: |
          echo "newbranchname=mewmba-${{ github.head_ref || github.ref_name }}-generated-protos" >> $env:GITHUB_OUTPUT
          echo "oldbranchname=${{ github.head_ref || github.ref_name }}" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        id: commit_changes
        with:
          author_name: Mewmba
          author_email: mewmba@trinsic.id
          message: 'Generated code from proto files on branch ${{ steps.new-branch-name.outputs.oldbranchname }}'
          new_branch: ${{ steps.new-branch-name.outputs.newbranchname }}
          push: '--force --set-upstream origin ${{ steps.new-branch-name.outputs.newbranchname  }}'

      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: ${{ steps.commit_changes.outputs.committed == 'true' }}
        with:
          source_branch: ${{ steps.new-branch-name.outputs.newbranchname }}
          destination_branch: ${{ steps.new-branch-name.outputs.oldbranchname }}
          pr_title: "Generated Protos for ${{ steps.new-branch-name.outputs.oldbranchname }}"
          pr_body: ":rocket: Generated protos"
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
