name: ".NET"

on:
  pull_request:
    branches:
      - main
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
  push:
    branches:
      - main
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          dotnet restore
          dotnet build -c Release
          dotnet test -c Release -v n
        working-directory: ./dotnet
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
