name: "Connect SDK Build"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'connect/swagger**'
      - '.github/workflows/*typescript*'
      - "devops/**"

jobs:
  build_test:
    strategy:
      matrix:
        swagger_json: ['connect/swagger_api.json']
        language: [['typescript-fetch', 'connect/typescript'], ['csharp', 'connect/csharp']]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Setup Node v20
        with:
          node-version: 20
          cache: 'npm'
      - name: Build Connect TypeScript SDK
        run: ./devops/make-swagger.ps1 -language ${{ matrix.language[0] }} -swaggerFile ${{ matrix.swagger_json }} -outputFolder ${{ matrix.language[1] }}
        shell: pwsh

      - name: Format code
        run: |
          npm ci
          npm run build:prettier
        working-directory: connect/typescript

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
