name: Java

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
      - "devops/**"

jobs:
  build-and-test-java:
    name: Build
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows], [macos-latest, macos] ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Download ${{ matrix.os-artifact[0] }} binaries
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          workflow: "build-libs.yml"
          path: ./libs/${{ matrix.os-artifact[1] }}
          repo: trinsic-id/okapi
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ matrix.os-artifact[1] }}
      - name: Build with Gradle
        run: |
          python ../devops/build_sdks.py --language=java
          gradle build
        shell: pwsh
        working-directory: java
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This has github maven package repo permissions
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          JAVA_LIBRARY_PATH: "${{ github.workspace }}/libs" # https://stackoverflow.com/a/60128194 - MacOS doesn't allow LD_LIBRARY_PATH.
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
      - name: Upload Unit Test Results - Java
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Java Unit Test Results (${{ matrix.os-artifact[0] }})
          path: 'java/build/test-results/test/TEST-*.xml'

  publish-test-results-java:
    name: Publish Java Test Results
    needs: build-and-test-java
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: java_artifacts
      - name: Publish Test Report - Java
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'java_artifacts/**/*.xml'
          check_name: Java Test Report
