name: "TypeScript"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'node/**'
      - 'web/**'
      - 'proto/**'
      - '.github/workflows/*typescript*'
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - 'node/**'
      - 'web/**'
      - 'proto/**'
      - '.github/workflows/*typescript*'
      - "devops/**"

jobs:
  build_test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        target: [ "web" ]
        node-version: [ 14, 16 ]
        node-http-protocol: ["true", "false"]
    defaults:
      run:
        working-directory: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v1
      - uses: arduino/setup-protoc@v1
      - uses: actions/setup-node@v3
        name: Setup Node v${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build
          npm run test
        name: "Build and Test Package: Node v${{ matrix.node-version }} with HTTP1 protocol=${{ matrix.node-http-protocol }}"
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
          TEST_SERVER_NODE_PROTOCOL: ${{ matrix.node-http-protocol }}
        shell: pwsh
