name: Build Java SDK

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"

jobs:
  build-and-test-java:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          repo: trinsic-id/okapi
      - name: Build with Gradle
        run: |
          python ../devops/build_sdks.py
          gradle build
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          TEST_SERVER_ENDPOINT: staging-internal.trinsic.cloud
          TEST_SERVER_PORT: 443
          TEST_SERVER_USE_TLS: true
      - name: Upload Unit Test Results - Java
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Java Unit Test Results (${{ matrix.os-artifact[0] }})
          path: 'java/build/test-results/test/TEST-*.xml'

  publish-test-results-java:
    name: Publish Java Test Results
    needs: build-and-test-java
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Test Report - Java
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'artifacts/**/*.xml'
          check_name: Java Test Report
