name: Java

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/*java*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          repo: trinsic-id/okapi
      - name: Build with Gradle
        run: |
          ./devops/BuildJava.ps1 -GitTag ${{ github.ref }} -TestOutput "test_output_${{ matrix.os }}.xml" -ArtifactName "${{ matrix.artifact_name }}"
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          TEST_SERVER_ENDPOINT: staging-internal.trinsic.cloud
          TEST_SERVER_PORT: 443
          TEST_SERVER_USE_TLS: true
      - uses: actions/upload-artifact@v2
        if: (${{ matrix.os }} == 'ubuntu-latest')
        with:
          name: Package
          path: java/build/libs
