name: ".NET"

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
      - "devops/**"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          dotnet workload install ios
          dotnet restore
          dotnet build -c Release -f net6.0 -p:IsBrowser=true ./Trinsic
          dotnet build -c Release
          dotnet test -c Release -v n /p:CollectCoverage=true /p:CoverletOutput=./ /p:CoverletOutputFormat=cobertura
        working-directory: ./dotnet
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          directory: dotnet
          token: ${{ secrets.CODECOV_TOKEN }}
