name: "TypeScript"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'web/**'
      - 'proto/**'
      - '.github/workflows/*typescript*'
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'proto/**'
      - '.github/workflows/*typescript*'
      - "devops/**"

jobs:
  build_test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 14, 16, 18 ]
        working-directory: [ node, web ]
    defaults:
      run:
        working-directory: web/trinsic-${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        name: Setup Node v${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
        working-directory: web
      - run: |
          npm install
          npm run test
        name: "Build and Test Package: Node v${{ matrix.node-version }}"
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
        shell: pwsh
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          directory: web
          token: ${{ secrets.CODECOV_TOKEN }}
