name: Build/Test Documentation

on:
  workflow_call:
  pull_request:
    branches:
      - main
  # We don't have path dependencies because we code-inject the samples, and we want to ensure those are all in the right places.
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: |
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
      - run: mkdocs build

