name: Build Proto Files
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "proto/**"
      - "devops/*.py"
  pull_request:
    paths:
      - "proto/**"
      - "devops/**"

jobs:
  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protobuf plugins
        run: |
          pip install -r ./devops/requirements.txt
          python ./devops/generate_proto_files.py --download-plugins --language=none
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Compile proto files
        run: |
          python ./devops/generate_proto_files.py --language=all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4