name: "Node: Build, Test"

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run: 
        working-directory: ./node
    steps:
      - uses: actions/checkout@v1
        with: 
          node-version: ${{ matrix.node-version }}
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: npm test