name: "Node: Build, Test"

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run: 
        working-directory: ./node
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with: 
          token: ${{ secrets.ACCESS_TOKEN }}
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: npm ci
      - run: npm run build
      - run: npm test