# SEE: https://docs.github.com/en/github/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks <>
name: "PR Validation"

# SEE: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions <>
# SEE: https://docs.microsoft.com/en-us/cli/azure/ <>
on:
  workflow_dispatch:
    pull_request:
      branches:
        - main

concurrency:
  group: prvalidate
  cancel-in-progress: true

jobs:
  verify_formatting:
    name: Verify formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install prettier
      - name: Run Prettier validation
        run: npx prettier --check ./web/src/
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run Go format validation
        run: |
          GOFMT_TARGETS=$(gofmt -s -l -e .)
          if [ -n "$GOFMT_TARGETS" ]; then
          echo "[warn] Code style issues found in the below files. Forgot to run go fmt?"
          echo $GOFMT_TARGETS
          exit 1
          fi
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Run dotnet format validation
        run: dotnet format Server.sln --verify-no-changes --no-restore
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run python format validation
        run: |
          python -m pip install black
          python -m black ./python --check
      