name: ".NET (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version (leave empty for latest release)'
        required: false
  release:
    types: [published, prereleased]

jobs:
  publish:
    name: Publish to nuget.org
    runs-on: macos-latest
    environment:
      name: nuget.org
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - run: |
          dotnet workload install ios
          dotnet restore
          dotnet build -c Release
          dotnet pack -p:Configuration=Release -p:PackageVersion=${{ steps.setversion.outputs.packageVersion }}
          dotnet pack -p:Configuration=Release -p:PackageVersion=${{ steps.setversion.outputs.packageVersion }} -p:IsBrowser=true -p:PackageId=Trinsic.Web
        working-directory: ./dotnet/Trinsic
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            ./dotnet/**/Release/*.nupkg
            ./dotnet/**/Release/*.snupkg
      - name: Push packages to Nuget
        run: |
          foreach ($item in get-childitem ./ -recurse | select-object FullName | where { $_.FullName.EndsWith(".nupkg") })
          {
            nuget push $item.FullName -ApiKey "${{ secrets.NUGET_API_KEY }}" -Source https://api.nuget.org/v3/index.json -SkipDuplicate
          }
        shell: pwsh
        working-directory: ./dotnet



