name: "Connect SDK / Dotnet (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version (leave empty for next patch version)'
        required: false

jobs:
  publish:
    name: Publish to nuget.org
    runs-on: ubuntu-latest
    environment:
      name: nuget.org
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Set version
        run: ./.github/workflows/connect/set-connect-version.ps1 -Version ${{ github.event.inputs.packageVersion || 'NEXTPATCH' }} -Language "csharp"
        shell: pwsh
      - name: Build!
        run: ./.github/workflows/connect/build-dotnet.ps1
        shell: pwsh
      - name: Push packages to Nuget
        run: ./.github/workflows/connect/release-dotnet.ps1 -ApiKey ${{ secrets.NUGET_API_KEY }}
        shell: pwsh

      - name: Mewmba Create PR
        id: mewmba-create-pr
        uses: trinsic-id/mewmba/actions/mewmba-pr@main
        with:
          apiGithubToken: ${{ secrets.GITHUB_TOKEN }}
          commitMessage: "Updated dotnet released package version"
          githubAssignee: ${{ github.actor }}
          prTitle: "Updated dotnet Released Package Version"
          githubBranch: "main"
          githubWorkingDirectory: "."
          githubRepository: "trinsic-id/sdk"



