name: "Java (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  release:
    types: [published, prereleased]

jobs:
  build:
    name: Build + Publish Java
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.22.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
          repo: trinsic-id/okapi
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: Publish package
        run: |
          python ../devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }} --language=java
          gradle jar
        working-directory: java
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.API_GITHUB_TOKEN }}
          file: java/build/libs/trinsic-services-${{ steps.setversion.outputs.packageVersion }}.jar
          asset_name: trinsic-services-${{ steps.setversion.outputs.packageVersion }}.jar
          tag: ${{ steps.setversion.outputs.releaseVersion }}
          overwrite: true
