name: ".NET (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version (leave empty for latest release)'
        required: false
  release:
    types: [published, prereleased]

jobs:
  publish:
    name: Publish to nuget.org
    runs-on: macos-latest
    environment:
      name: nuget.org
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Generate Package Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/sdk/releases/latest' `
            -Headers @{ "Authorization" = "Token $env:API_GITHUB_TOKEN"} | ConvertFrom-Json
          $version = if ([string]::IsNullOrEmpty($env:MANUAL_VERSION)) { $json.tag_name.Trim("v") } else { $env:MANUAL_VERSION.Trim("v") }
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          MANUAL_VERSION: ${{ github.event.inputs.packageVersion }}
      - run: |
          dotnet workload install ios
          dotnet restore
          dotnet build -c Release
          dotnet pack -p:Configuration=Release -p:PackageVersion=$env:PACKAGE_VERSION
          dotnet pack -p:Configuration=Release -p:PackageVersion=$env:PACKAGE_VERSION -p:IsBrowser=true -p:PackageId=Trinsic.Web
        working-directory: ./dotnet/Trinsic
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            ./dotnet/**/Release/*.nupkg
            ./dotnet/**/Release/*.snupkg
      - name: Push packages to Nuget
        run: |
          foreach ($item in get-childitem ./ -recurse | select-object FullName | where { $_.FullName.EndsWith(".nupkg") })
          {
            nuget push $item.FullName -ApiKey "${{ secrets.NUGET_API_KEY }}" -Source https://api.nuget.org/v3/index.json -SkipDuplicate
          }
        shell: pwsh
        working-directory: ./dotnet



