name: Release Python SDK

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - main

jobs:
  release_testpypi:
    name: Python Package deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build, Test, Pack
        run: ./devops/BuildPython.ps1 -GitTag ${{ github.ref }}
        shell: pwsh
      - name: Push packages to release
        if: |
          github.event_name == 'release' &&
          github.event.action == 'published'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./python/dist/*
          file_glob: true
          asset_name: "python"
          tag: ${{ github.ref }}
          overwrite: true
          body: "Python SDK package"
      - name: Publish distribution 📦 to PyPI
        if: |
          github.event_name == 'release' &&
          github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://pypi.org/legacy/
          packages_dir: ./python/dist
          skip_existing: true