name: Documentation (release)

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Get everything so that the `mkdocs-git-authors` plugin answers correctly
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protobuf plugins
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          pip install -r ./devops/requirements.txt
      - run: python ./devops/generate_proto_files.py --language docs # Generate protobuf documentation files
      - run: mkdocs gh-deploy --remote-branch gh-pages --site-dir ./docs-html --force

