name: Ruby Gem

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
          repo: trinsic-id/okapi
      - name: Install dependencies
        run: |
          bundle config set rubygems.pkg.github.com ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
        working-directory: ruby
      - name: Build and run tests
        run: ./devops/BuildRuby.ps1 -GitTag ${{ github.ref }}
        shell: pwsh
        env:
          TRINSIC_SERVER_ADDRESS: http://pr-development.centralus.azurecontainer.io:5000/
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          github_token: ${{secrets.GITHUB_TOKEN}}