name: Documentation (release)

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: |
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
          pip install -r ./devops/requirements.txt
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install protoc plugins
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          go install github.com/trinsic-id/protoc-gen-json@latest
      - run: python ./devops/generate_proto_files.py --language=docs # Generate protobuf documentation files
      - run: mkdocs gh-deploy --remote-branch gh-pages --site-dir ./docs-html --force

