name: "Release Installers"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version (leave empty for latest release)'
        required: false
  pull_request:
    paths:
      - ".github/workflows/release-installers.yml"

env:
  packageId: trinsic.cli

jobs:
  set_version:
    name: Set Version
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.setversion.outputs.packageVersion }}
      releaseVersion: ${{ steps.setversion.outputs.releaseVersion }}
    steps:
      - uses: trinsic-id/set-version@main
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}

#  instruqt:
#    name: Update Instruqt Demo
#    needs: [ set_version ]
#    uses: trinsic-id/tutorials/.github/workflows/update-samples.yml@main
#    with:
#      callerVersion: ${{ needs.set_version.outputs.packageVersion }}
#    secrets: inherit

  homebrew:
    name: Update Homebrew Formula
    needs: [ set_version ]
    uses: trinsic-id/homebrew-tap/.github/workflows/update-formula.yml@main
    with:
      callerVersion: ${{ needs.set_version.outputs.packageVersion }}
    secrets: inherit

  windows:
    name: Update WIX Package
    needs: [ set_version ]
    # https://github.com/TechWatching/winget-package-submission/blob/main/.github/workflows/winget-submission.yml
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        # Uses the REPO PUSH token to ensure we have the proper permissions.
        run:  |
          $Version = "${{ needs.set_version.outputs.packageVersion }}"
          $ReleaseVersion = "${{ needs.set_version.outputs.releaseVersion }}"
          $Version = $Version.Replace("v","")
          $ReleaseVersion = $ReleaseVersion.Replace("v","")
          Write-Host "Updating winget msi to $Version"

          $DownloadUrl = "https://github.com/trinsic-id/sdk/releases/download/v$ReleaseVersion/trinsic-$Version-x86_64.msi"
          $WingetCreate = "wingetcreate.exe"
          iwr https://aka.ms/wingetcreate/latest -OutFile $WingetCreate

          .\wingetcreate.exe update "trinsic.cli" -s -v $Version -u $DownloadUrl -t ${{ secrets.WINGET_PUSH_TOKEN }}
          Remove-Item $WingetCreate
        shell: pwsh
