name: Documentation (release)

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Get everything so that the `mkdocs-git-authors` plugin answers correctly
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: python ./devops/generate_proto_files.py --language docs # Generate protobuf documentation files
      - run: mkdocs gh-deploy --remote-branch gh-pages --site-dir ./docs-html --force

