name: Documentation (release)

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install -r ./docs/requirements.txt
          pip install -r ./python/requirements.txt
          pip install git+https://github.com/fundthmcalculus/mkdocs-codeinclude-plugin.git@support-lang-based-extensions
      - run: mkdocs gh-deploy --remote-branch gh-pages --site-dir ./docs-html --force

