name: "Ruby (release)"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
          repo: trinsic-id/okapi
      - name: Install dependencies
        run: |
          bundle config set rubygems.pkg.github.com ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
        working-directory: ruby
      - name: Build and run tests
        run: |
          gem install bundler
          gem install rspec
          bundle install
          python ../devops/build_sdks.py --package-version=${{ github.event.inputs.packageVersion }}
          bundle exec rake
          rake test
          exit 0
        shell: pwsh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          RUBY_DLL_PATH: "${{ github.workspace }}/libs"  # Required for Ruby on Windows
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          github_token: ${{secrets.GITHUB_TOKEN}}
