name: .NET (prod test)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test-dotnet.yml"
      - "samples/dotnet/**"

jobs:
  prod-test-net:
    name: .NET - samples - prod test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build, Test, Pack
        run: |
          dotnet restore
          dotnet build
          dotnet run
        shell: pwsh
        working-directory: samples/dotnet