# This action is used to manually invoke a full test against a certain environment
# Requires an endpoint input which you can get from the Pulumi outputs

name: Test Environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'the environment to test'
        required: false
        default: 'Staging'

jobs:
  test_infra:
    name: Run CLI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./cli/test/Run-Demo.ps1 -Environment ${{ inputs.environment }} -CommandPath ./cli/target/debug/trinsic
