name: Typescript (prod test)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test-node.yml"
      - "samples/web/**"

jobs:
  prod-test-node:
    name: Node - samples - prod test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build, Test, Pack
        run: |
          npm ci
          npm run main
        shell: pwsh
        working-directory: samples/node
