name: Golang (prod test)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test-golang.yml"
      - "samples/go/**"

jobs:
  prod-test-golang:
    name: Golang - samples - prod test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build, Test, Pack
        run: |
          go run sample.go
        shell: pwsh
        working-directory: samples/go
