# This action is used to manually invoke a full test against a certain environment
# Requires an endpoint input which you can get from the Pulumi outputs

name: Test Environment


on:
  pull_request:
    paths:
      - ".github/workflows/test-infrastructure.yml"
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'the environment to test'
        required: false
        default: 'Staging'

jobs:
  test-infra:
    name: Test Infrastructure ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew tap trinsic-id/tap
          brew install trinsic-cli
      - name: Run CLI Demos
        run: cli/test/Run-Demo.ps1 -Environment ${{ inputs.environment }} -CommandPath ./target/debug/trinsic
        shell: pwsh
        working-directory: samples/java