# This action is used to manually invoke a full test against a certain environment
# Requires an endpoint input which you can get from the Pulumi outputs

name: Test Environment

on:
  pull_request:
    paths:
      - ".github/workflows/test-infrastructure.yml"
      - "cli/test/Run-Demo.ps1"
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'the environment to test'
        required: false
        default: 'Staging'

jobs:
  test-infra:
    name: Test Infrastructure via HTTP2 ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # Because called actions run in caller repository, we have to be explicit here.
      - uses: actions/checkout@v3
        with:
          repository: trinsic-id/sdk
          path: ./sdk
      - uses: actions/setup-node@v3
        name: Setup Node v18
        with:
          node-version: 18
      - run: |
          npm ci
          npm run test:node
        env:
          TRINSIC_ENVIRONMENT: ${{ inputs.environment }}
        name: "Run grpc tests"
        shell: pwsh
        working-directory: ./sdk/samples/grpc-web

  test-infra-grpc-web:
    name: Test Infrastructure via grpc-web ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # Because called actions run in caller repository, we have to be explicit here.
      - uses: actions/checkout@v3
        with:
          repository: trinsic-id/sdk
          path: ./sdk
      - uses: actions/setup-node@v3
        name: Setup Node v18
        with:
          node-version: 18
      - run: |
          npm ci
          npm run test:browser -- --trinsic_environment="${{ inputs.environment }}"
        name: "Run grpc-web tests"
        shell: pwsh
        working-directory: ./sdk/samples/grpc-web
