# This action is used to manually invoke a full test against a certain environment
# Requires an endpoint input which you can get from the Pulumi outputs

name: Test Environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'the environment to test'
        required: false
        default: 'Staging'

jobs:
  test_infra:
    uses: ./.github/workflows/build-rust.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
